#!/usr/bin/env bash
# Script displays content of file about user....but not FIZZBUZZ!

FILE="/etc/passwd"

if [ -e "$FILE" ]; then

  cut -d ':' -f1,3,6 "$FILE"
else

  echo "The $FILE file does not exist."
fi
