#!/usr/bin/env bash
# This runs Best School ten times but adds Hi for the 9th adds Hi

count=0

while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
